export const ADD_EVENT = "ADD_EVENT";

export const REMOVE_EVENT = "REMOVE_EVENT";

export const EDIT_EVENT = "EDIT_EVENT";

export const REMOVE_FROM_NOTIFICATION_QUE = "REMOVE_FROM_NOTIFICATION_QUE";
